# Generated by Django 3.2.19 on 2023-05-22 11:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recipes', '0002_alter_ingredientamount_options'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tag',
            name='color',
            field=models.CharField(max_length=11, verbose_name='Цвет в HEX'),
        ),
    ]
